name: Auto Wiki Generator

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run generator
        run: python3 generate.py

      - name: Commit changes
        run: |
          git config user.name "wiki-bot"
          git config user.email "wiki-bot@users.noreply.github.com"

          git add page used.json

          git diff --cached --quiet && echo "No changes" || (
            git commit -m "Auto wiki pages"
            git push
          )
