name: Auto Wiki Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install node-fetch@2

      - name: Run generator
        run: node generate.js

      - name: Commit changes
        run: |
          git config user.name "wiki-bot"
          git config user.email "bot@wiki.com"
          git add .
          git commit -m "Auto articles" || echo "No changes"
          git push
